apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: bsc-frontend
  name: bsc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bsc-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/bank-statement-converter-default: "true"
        io.kompose.service: bsc-frontend
    spec:
      containers:
        - image: bsc-frontend
          name: bsc-frontend
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
      restartPolicy: Always
