apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: bsc-backend
  name: bsc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bsc-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/bank-statement-converter-default: "true"
        io.kompose.service: bsc-backend
    spec:
      containers:
        - env:
            - name: BACKEND_CORS_ORIGINS
              value: '["*"]'
          image: bsc-backend
          name: bsc-backend
          ports:
            - containerPort: 8000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
