apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: ytgpt-backend
  name: ytgpt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ytgpt-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/yt-gpt-default: "true"
        io.kompose.service: ytgpt-backend
    spec:
      containers:
        - env:
            - name: CORS_ORIGINS
              value: '["{{ .Values.ingress.host }}"]'
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
          image: jpdeoliveiraferreira/ytgpt-backend:latest
          name: ytgpt-backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
